name: Melon Ticket Checker

on:
  schedule:
    - cron: '*/5 * * * *' # æ¯5åˆ†é˜
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check Tickets
        id: check
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212702
          schedule-id: 100003
          seat-id: 1_0
          # ä¸ç”¨ Slack
          message: 'ğŸŸï¸ æœ‰ç¥¨äº†å¿«æ¶ï¼'

      - name: Send Discord Notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "ğŸŸï¸ Melon Ticket å¯èƒ½æœ‰ç¥¨äº†ï¼å¿«å»æŸ¥çœ‹ï¼"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
